version: '3.2'
services:
    nginx:
       image : nginx:stable
       networks:
         - def_network
       restart: always
       volumes:
           - <your_path>:/etc/nginx/conf.d:ro
       ports:
           - 80:80
       depends_on:
           - app
       deploy:
           resources:
               limits:
                  cpus: '0.25'
                  memory: 256M


    db:
       image: mariadb
       networks:
         - def_network
       command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
       restart: always
       volumes:
           - <your_path>:/var/lib/mysql
       environment:
          - MYSQL_ROOT_PASSWORD=<your_password>
          - MYSQL_PASSWORD=<your_password>
          - MYSQL_DATABASE=<your_password>
          - MYSQL_USER=<your_password>
       deploy:
           resources:
               limits:
                   memory: 256M


    redis:
        image: redis:alpine
        networks:
            - def_network
        ports:
           - 6379:6379
        restart: always
        volumes:
            - <your_path>:/data
            - <your_path>:/usr/local/etc/redis/
        deploy:
            resources:
                limits:
                    memory: 128M


    app:
      image: nextcloud
      networks:
         - def_network 
      links:
          - db
          - redis
      volumes:
          - <your_path>:/var/www/html/custom_apps
          - <your_path>:/var/www/html/data
          - <your_path>:/var/www/html/
      restart: always
      deploy:
          resources:
              limits:
                  memory: 512M

networks:
         def_network:
