version: '3.2'
services:
    nginx:
       image : nginx:stable
       networks:
           - def_network
       restart: always
       volumes:
           - /etc/nginx/conf.d:/etc/nginx/conf.d:ro
           - /var/ssl:/var/ssl/:ro 
       ports:
           - 80:80
       depends_on:
           - app
       deploy:
           resources:
               limits:
                  cpus: '0.25'
                  memory: 256M


    db:
       image: mariadb
       networks:
           - def_network
       command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
       restart: always
       volumes:
           - /var/next/mysql:/var/lib/mysql
       environment:
          - MYSQL_ROOT_PASSWORD=nextcloud
          - MYSQL_PASSWORD=nextcloud
          - MYSQL_DATABASE=nextcloud
          - MYSQL_USER=nextcloud
       deploy:
           resources:
               limits:
                   memory: 256M


    redis:
        image: redis:alpine
        networks:
           - def_network
        ports:
           - 6379:6379
        restart: always
        volumes:
            - /var/next/redis/data:/data
            - /var/next/redis/etc/:/usr/local/etc/redis/
        deploy:
            resources:
                limits:
                    memory: 512M


    app:
      image: nextcloud
      networks:
          - def_network
      links:
          - db
          - redis
      volumes:
          - /var/next/custom_apps:/var/www/html/custom_apps
          - /var/next/data:/var/www/html/data
          - /var/next/html:/var/www/html/
      restart: always
      deploy:
          resources:
              limits:
                  memory: 512M

networks:
         def_network:
